### ISSUE TITLE
Will this be made available under an OSS licence?

### ISSUE THREAD

**Issue by VagishVela** [laurodev/Odamy#3]
Looks like there isn't an open source license yet. Not sure if this is intentional or not.

**Comment by laurodev** [comment]
Oh wow @VagishVela! You're the first person to contribute to my first real project. Thanks man!👍 

Yes, this will have OSS licence. Let me figure out how to add it.

**Comment by VagishVela** [comment]
@laurodev Just create a LICENSE.md file with the particular license and github will even add the little license logo to the stats bar of the repo.

Oh and by the way, I found this repo through: https://www.reddit.com/r/webdev/comments/5a9qj0/odamy_udemy_but_open_source_create_and_sell/

**Comment by laurodev** [comment]
@VagishVela Thanks! Done. 👍
